### ISSUE TITLE
Would have been nice but can't get it to work

### ISSUE THREAD

**Issue by RaphaelJenni** [willhlaw/firestore-security-tests#3]
The idea is very nice and I would love to use it but I just can't get it to work. I'm jumping from one error to the other. Looking forward to a working and well documented version of this :)

**Comment by willhlaw** [comment]
Sorry about your issues, @RaphaelJenni. Do you remember any specific errors? 

I haven't gone through setting up a new project or trying this in the last month. Has anyone else had success or failures?

Otherwise, I guess you can just keep watching the repo when there are updates. I have improvements in mind, but I have no timeline.
